schema: src/services/client-schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://countries.trevorblades.com/
      headers:
        user-agent: TS GraphQL
      introspect: false
